POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Doc",
  "description": "Curso top"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/3f8af612-080c-4943-b176-67aadbd95858
